/** Mean average prices (₱) per piece (or per single unit: tube/roll/can) — Philippines market research. */
export const CONSUMABLE_DEFAULT_PRICES: Record<string, number> = {
  'Self-tapping screws': 4,
  'Concrete screws': 5,
  'Mounting screws': 2.5,
  'Small mounting screws': 1.5,
  'Expansion bolts': 35,
  'Anchor bolts': 95,
  'Expansion anchors': 28,
  'Wall plugs / Rawl plugs': 35,
  'Wall anchors': 40,
  'Washers': 3,
  'Nuts & bolts': 2,
  'Assorted screws': 2,
  'Silicone sealant (weatherproof)': 185,
  'Fire-rated silicone sealant': 2050,
  'Expanding foam': 520,
  'Firestop foam': 2620,
  'Firestop putty': 1400,
  'Firestop sealant': 1900,
  'Teflon tape': 22,
  'Thread sealant': 95,
  'Pipe joint compound': 110,
  'Gaskets': 45,
  'O-rings': 15,
  'Rust-proof spray': 280,
  'Anti-rust coating': 650,
  'Electrical tape': 55,
  'Heat shrink tubing': 800,
  'Wire ferrules': 12,
  'Wire connectors': 8,
  'Terminal lugs': 25,
  'Terminal connectors': 18,
  'End-of-line resistor covers': 35,
  'Cable markers / labels': 220,
  'Zone labels': 45,
  'Warning stickers': 35,
  'Labels / asset tags': 55,
  'Permanent marker': 45,
  'Marker pens': 35,
  'Cleaning alcohol': 95,
  'Cleaning wipes': 120,
  'Red touch-up paint': 180,
  'Touch-up paint': 165,
  'Double-sided industrial tape': 95,
  'Velcro straps': 65,
  'Rubber spacers': 25,
  'Drill bits': 140,
  'Cutting discs': 85,
  'Grinding discs': 95,
  'Welding rods': 55,
  'Lubricating oil': 620
};

